// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Parcial2_AriasRoldanNatalia.DAL;

#nullable disable

namespace Parcial2_AriasRoldanNatalia.Migrations
{
    [DbContext(typeof(DataBaseContext))]
    [Migration("20230415182637_UpdateFieldTypeDate")]
    partial class UpdateFieldTypeDate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Parcial2_AriasRoldanNatalia.DAL.Entities.Entrance", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Entrances");
                });

            modelBuilder.Entity("Parcial2_AriasRoldanNatalia.DAL.Entities.Ticket", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("EntranceGateid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UseDate")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.HasIndex("EntranceGateid");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("Parcial2_AriasRoldanNatalia.DAL.Entities.Ticket", b =>
                {
                    b.HasOne("Parcial2_AriasRoldanNatalia.DAL.Entities.Entrance", "EntranceGate")
                        .WithMany()
                        .HasForeignKey("EntranceGateid");

                    b.Navigation("EntranceGate");
                });
#pragma warning restore 612, 618
        }
    }
}
